const fs = require('fs');
const p = 'src/components/BrandsCarousel.tsx';
let s = fs.readFileSync(p, 'utf8');
const checks = [];
checks.push(['has doubledLogos', s.includes('doubledLogos')]);
checks.push(['has tripledLogos def', s.includes('tripledLogos')]);
s = s.split('{doubledLogos.map((brand, idx)').join('{tripledLogos.map((brand, idx)');
s = s.split('group/marquee').join('sponsor-wrap');
s = s.split('animate-[marqueeScroll_35s_linear_infinite] group-hover/marquee:[animation-play-state:paused]').join('animate-marquee sponsor-track');
s = s.split('hover:scale-115').join('hover:scale-105');
s = s.split('group-hover:scale-135 sm:group-hover:scale-145').join('group-hover:scale-110');
s = s.split('py-6 sponsor-wrap">').join('py-6 sponsor-wrap" onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)}>');
s = s.split('animate-marquee sponsor-track w-max').join('animate-marquee sponsor-track" + (paused ? " marquee-paused" : "") + " w-max');
fs.writeFileSync(p, s);
console.log('sponsor fixed. checks=' + JSON.stringify(checks));
console.log('verify tripled usage: ' + s.includes('{tripledLogos.map'));
console.log('verify paused state: ' + s.includes('marquee-paused'));
